---
title:
  - type: main
    text: Bewerbung
  - type: subtitle
    text: André Lademann
creator:
  - role: author
    text: André Lademann
identifier:
  - scheme: DOI
    text: doi:10.234234.234/33
belongs-to-collection: resume
publisher: "Publisher: https://github.com/vergissberlin"
lang: de
rights: © 2022 André Lademann, CC BY-NC
ibooks:
  version: 1.0.0
  ipad-orientation-lock: portrait-only
  specified-fonts: true|
cover-image: Content/Media/Cover/Cover-epub.png
